flowchart LR
    log0(attributes: 
&nbsp;&nbsp;query_time: &quot;0.776920&quot;
severity_number: 0 
severity_text:
    )
    log1(attributes: 
&nbsp;&nbsp;query_time: &quot;0.776920&quot;
&nbsp;&nbsp;slow: true
severity_number: 9
severity_text: INFO
    )
    log0 --> log1
