flowchart LR
    log0(attributes: 
&nbsp;&nbsp;query_time: 0.776920
&nbsp;&nbsp;lock_time: 0.000002
&nbsp;&nbsp;rows_sent: 1834
&nbsp;&nbsp;rows_examined: 18755
&nbsp;&nbsp;query: SELECT * FROM my_table
severity_number: 0 
severity_text:
    )
    log1(attributes: 
&nbsp;&nbsp;query_time: 0.776920
&nbsp;&nbsp;lock_time: 0.000002
&nbsp;&nbsp;rows_sent: 1834
&nbsp;&nbsp;rows_examined: 18755
&nbsp;&nbsp;query: SELECT * FROM my_table
&nbsp;&nbsp;query: super_slow: true
severity_number: 9
severity_text: INFO
    )
    log0 --> log1
