flowchart LR
    log0("cache: {}")
    log1(cache:
&nbsp;&nbsp;epoch_timestamp: 1730239218,
&nbsp;&nbsp;trace_id: 959295b1,
&nbsp;&nbsp;span_id: 405b51fd,
&nbsp;&nbsp;name: my-app,
&nbsp;&nbsp;env: prod,
&nbsp;&nbsp;log: network error
    )
    log0 --> log1
