flowchart LR
    log0(attributes:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.mycompany.io/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
    )
    log1(attributes:
&nbsp;&nbsp;k8s.pod.labels:
&nbsp;&nbsp;&nbsp;&nbsp;app: my-app
&nbsp;&nbsp;&nbsp;&nbsp;mycompany.io/arch: x86
&nbsp;&nbsp;&nbsp;&nbsp;environment: prod
&nbsp;&nbsp;test: true
    )
    log0 --> log1

    log2(attributes:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.mycompany.io/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
cache:
    )
    log3(attributes:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.mycompany.io/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
cache:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.mycompany.io/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
    )
    log2 --> log3

    log4(attributes:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.mycompany.io/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
cache:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.mycompany.io/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
    )
    log5(attributes:
&nbsp;&nbsp;test: true
cache:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.mycompany.io/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
    )
    log4 --> log5

    log6(cache:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.mycompany.io/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
    )
    log7(cache:
&nbsp;&nbsp;app: my-app
&nbsp;&nbsp;mycompany.io/arch: x86
&nbsp;&nbsp;environment: prod
    )
    log6 --> log7


    log8(attributes:
&nbsp;&nbsp;test: true
    )
    log9(attributes:
&nbsp;&nbsp;k8s.pod.labels:
&nbsp;&nbsp;&nbsp;&nbsp;app: my-app
&nbsp;&nbsp;&nbsp;&nbsp;mycompany.io/arch: x86
&nbsp;&nbsp;&nbsp;&nbsp;environment: prod
&nbsp;&nbsp;test: true
    )
    log8 --> log9
