flowchart LR
    log2(attributes:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.custom/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
cache:
    )
    log3(attributes:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.custom/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
cache:
&nbsp;&nbsp;k8s.pod.label.app: my-app
&nbsp;&nbsp;k8s.pod.label.custom/arch: x86
&nbsp;&nbsp;k8s.pod.label.environment: prod
&nbsp;&nbsp;test: true
    )
    log2 --> log3

